name: ZZU COMMUTE HELPER

on:
    workflow_dispatch:
    schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: UID
        uses: actions/checkout@v2
    
      - name: UPW
        env:
            UID: ${{201984230328}}
            UPW: ${{10113019}}
        run: bash ./script.sh $UID $UPW
